<?php require('Views/template/header.phtml') ;
require_once('Models/friendsData.php');
?>
<br>
    <table class="table table-hover">
        <thead>
        <tr><th>User ID</th><th>Username</th><th>Email</th><th>Photo</th><th>Location</th><th>status</th></tr>
        </thead>
        <tbody>
        <?php foreach ($userDataSet as $friend){
            echo'<tr> <td>' . $friend->getUserID() .
                '</td> <td>' . $friend->getUsername() .
                '</td> <td>' . $friend->getEmail() .
                '</td> <td>' . '<img src="users/' . $friend->getPhotoName() . ' " alt="no picture" />' .
                '</td> <td><p1>(</p1>' . $friend->getLat(),'<p1>, </p1>'.$friend->getLng() .
                '<p1>)</p1></td>';
            $status = $friend->getStatus();
            switch($status){//check the friendship status for user
                case 2://if user is friend display this / deal with it on request.html
                    echo '<td><p1>Already Friend</p1><br>
                          <form method="post" action="requests.php?id='.$friend->getFriendshipID().'" class="form text-primary">                        
                            <input class="friendBtn" type="submit" name="Remove" value ="Remove Friend" id="removebtn"> 
                           </form>
                    </td>';
                    break;
            }
                '</tr>';
        }
        ?>
        </tbody>
    </table>
<br>
<div id="friend_map"></div><br>
<?php require('template/footer.phtml') ?>
