    </div>
    </div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script>
    const dropdown = document.getElementById('dropdown-menu');
    const navBar = document.getElementById('myNavbar');

    dropdown.addEventListener('click', () => {
        navBar.classList.toggle('show');
    });
</script>
    <script src="/js/OpenLayers/OpenLayers.js"></script>
    <script src="/js/map.js"></script>
    <footer class="footer">
        <p>Web-site development using the MVC design pattern and the Bootstrap CSS framework</p>
    </footer>
    </body>
</html>